name: Push to Amazon ECR
author: jwalton
description: Push a docker image to (or pull from) Amazon ECR.
inputs:
  source-access-key-id:
    required: true
    description: Source Access key for IAM User.
  source-secret-access-key:
    required: true
    description: Source Secret access key for IAM User.
  dest-access-key-id:
    required: true
    description: Destination Access key for IAM User.
  dest-secret-access-key:
    required: true
    description: Destination Secret access key for IAM User.
  images:
    required: true
    description: comman separated list of images to sync.
  region:
    description: AWS Region to use.  Defaults to eu-west-1.
    required: false
runs:
  using: node16
  main: 'dist/index.js'
branding:
  icon: upload
  color: orange
